language: java

jdk:
  - openjdk8

# Whitelist
branches:  
  only:
    - master

services:  
    # Enable docker service inside travis
    - docker

cache:
  directories:
    - $HOME/.m2

install:
    # Build the spring boot app and copy the result to the docker folder
    - mvn -B -Dspring.profiles.active=test clean install && cp target/mcp-identityregistry-core-latest.war docker/

before_script:  
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    # Build the docker image
    - docker build --no-cache -t dmadk/mc-identity-registry-api docker
    # Push the image to the repository
    - docker push dmadk/mc-identity-registry-api
    # Log out of docker
    - docker logout
